#+STARTUP: indent
#+title: Mitchell's School Task List
#+DESCRIPTION: School Tasks
#+ARCHIVE: %s_archive::

* General School Tasks 
** TODO GST - Pay School Tuition
 Cost is $375.00
* Math Todo List
** TODO MATH - Complete Week 1 Homework
DEADLINE: <2020-02-03 Mon> 
1.1:  3, 7, 9, 11, 27, 31, 34, 47, 63 (DONE)

1.2:  3, 4, 7, 10, 15 (DONE)

1.3:  1, 3, 5, 9, 17, 24, 27, 35, 51 (DONE)

1.4:  1, 3, 9, 13, 17, 21, 31 (DONE)

1.5:  1, 3, 5, 15, 18, 35-38, 47, 51, 63 (DONE)

2.1:  1, 3, 5, 6

Review, review, review!  This first week is mainly a whirlwind review of precalculus and algebra concepts and strategies, 
to make sure you remember your Encyclopedia of Functions.  Having this stuff solid will make the rest of the class go much smoother.  
Don't worry; I'll still be teasing some more calculus concepts this week, too!

Study Transformations and what different graphs of functions look like.
Be able to identify what a graph function is.

* Anthropogy Todo List
** TODO ANTHRO - Complete Week 2 Homework
*** Forum Questions
*** Video Questions
*** Inquiz
*** Canvas Quix
*** Read Chapter 2
Make Notes about the vocabulary of the chapter.  
If you don't know all the concepts thats ok just keep in mind the key words.
