#+STARTUP: indent
#+title: Mitchell's School Task List
#+DESCRIPTION: School Tasks
#+ARCHIVE: %s_archive::

* General School Tasks 
** TODO GST - Pay School Tuition
SCHEDULED: <2020-02-06 Thu>
Cost is $375.00
* Math Todo List
** TODO MATH - Week 2 homework
DEADLINE: <2020-02-12 Wed> SCHEDULED: <2020-02-05 Wed>
2.2:  1, 2, 4, 5, 9, 11, 13, 16, 19, 23, 31, 47

2.3:  2, 3, 7, 10, 11, 12, 17, 21, 23, 25, 35, 62

2.5:  3, 7, 10, 23, 25, 33, 37, 53

Chapter 2 homework!  Here we develop the tools (limits) that are necessary 
to establish our notion of the derivative (instantaneous rates of change).
* Anthropogy Todo List
** TODO ANTHRO - Complete Week 2 Homework
Make Notes about the vocabulary of the chapter.  
If you don't know all the concepts thats ok just keep in mind the key words.

Weeks 2 and 3 Overview

Welcome to Weeks 2 and 3 of the course, which will cover Chapter 2 of the Textbook. The next few weeks might feel a little tough for those that haven't had Biology recently, or have not had a lot of fun in previous science classes. Fear not! You will get through this!
This week we're going to do a quick dive through basic Genetics. Mostly, this means learning a lot of new vocabulary - pay attention to the words in bold in the text and consider making some flashcards so that you become familiar with them. These are probably terms that you'll read about in the news or in future courses, so they are worth learning.
For this chapter, don't get lost in the math. Recombination, where the math shows up, is a small part of this Chapter. You'll want to make sure that you have a basic understanding of how it works, but don't dwell on the math of allele frequencies. It's more important that you read through the entire chapter and pick up the vocabulary and the basic concepts of Mendelian inheritance, alleles vs genes, genotype and phenotype, the various steps that do from turning DNA into proteins, and the basic differences between DNA and RNA. Whew! 
You can always open the Canvas quiz (just don't hit Submit!) and take a look at the questions in this week's Quiz. That will give you a sense for the level of understanding that I'm looking for. 
Feel free to make use of the Course Questions Forum is you run into any questions about the material. Myself, or better yet other students, can jump in to answer questions! There are also some Chapter 2 Learning Resources to point you in the direction of some resources.

At the end of the Module you will be able to:
Explain how Mendel's laws are linked to the way cells replicate
Explain how the properties of DNA are consistent with the role of genes in inheritance
Describe how genes control the structure of proteins and influence the properties of organisms

Tasks to accomplish in this Module:
READ: Chapter 2 of the textbook, paying attention to learning the vocabulary - don't get bogged down in too many details!
INQUIZITIVE: Work on achieving 100% in Chapter 2. You should aim to have this finished prior to taking the Quiz in Canvas. Soft deadline of Tuesday, Feb 18 @ 11:59pm
READ: Through the page on Chapter 2 Learning Resources and watch the videos if you want to know more.
ANIMATION EXERCISE: Watch and complete the exercise on "From DNA to a Protein" DUE Feb 18 @ 11:59pm. You need to click the "Start Quiz" button to see the animation. The animation will show with the questions directly below it. This is an untimed exercise.
ANIMATION EXERCISE: Watch and complete the exercise on "Meiosis" DUE Feb 18 @ 11:59pm. 
QUIZ: The quiz in Canvas is on Chapter 2. DUE Tuesday, Feb 18 @ 4pm. NOTE: This is due earlier in the day than the other items on this list. This will be the case every week.
WATCH: The video "Cracking Your Genetic Code". As you watch the video, think about and answer the Questions on the video instructions page. These questions and their answers should become part of your study material for the next Midterm and the future Final Exam. These questions will NOT appear on the Canvas Quiz for Chapter 3.
FORUM: Respond to the video. Instructions are at the top of the forum area. Initial responses are DUE SATURDAY, Feb 15 @ 11:59pm. Peer responses are due Tuesday, Feb 18 @ 11:59pm. Your initial responses will require that you do about 30 minutes of extra reading / searching the internet before writing your response. Do not leave this until the last minute! I will give feedback to those that come in early, but entries closer to the deadline will not be given as much feedback. Feedback gives you an opportunity to raise your initial response grade if you do not earn full credit.
*** Forum Questions
*** Video Questions
*** Inquiz
*** Canvas Quix
*** Read Chapter 2
